/**
 * indexer.ts — Scan all rooms and generate INDEX.md for a memsudo palace.
 *
 * Scans areas/ (depth 2-3), lab/ (depth 2-3), and incubate/ (depth 2)
 * for CLAUDE.md files, parses status and now-focus, groups by category,
 * and writes a formatted INDEX.md to the palace root.
 *
 * Zero runtime dependencies — Bun fs/glob + path only.
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { parseStatus, parseNow } from "./markdown";

/** A single room entry parsed from a CLAUDE.md file. */
interface RoomEntry {
  /** Display name derived from directory basename */
  name: string;
  /** Relative path from palace root to the room directory */
  path: string;
  /** Category derived from path (clients, jobs, lab, etc.) */
  category: string;
  /** Status emoji or first word from **Status**: line */
  status: string;
  /** First meaningful line from ## Now section, truncated to 60 chars */
  now: string;
}

/**
 * Derive the category from a room's relative path.
 *
 * - areas/clients/X → "clients"
 * - areas/jobs/X → "jobs"
 * - areas/personal/X → "personal"
 * - areas/tools/X → "tools"
 * - lab/X → "lab"
 * - incubate/X → "incubate"
 */
function categoryFromPath(relPath: string): string {
  const parts = relPath.split("/");
  if (parts[0] === "areas" && parts.length >= 2) {
    return parts[1];
  }
  // lab/ or incubate/ — the top-level dir IS the category
  return parts[0];
}

/**
 * Scan the palace for all CLAUDE.md room files using Bun's glob.
 *
 * Scan patterns match the plan:
 *   areas at depth 2 and 3, lab at depth 2 and 3, incubate at depth 2.
 *
 * Skips files without a {@link parseStatus | Status} line (not room format).
 */
async function scanRooms(palaceRoot: string): Promise<RoomEntry[]> {
  const patterns = [
    "areas/*/*/CLAUDE.md",
    "areas/*/*/*/CLAUDE.md",
    "lab/*/CLAUDE.md",
    "lab/*/*/CLAUDE.md",
    "incubate/*/CLAUDE.md",
  ];

  const seen = new Set<string>();
  const rooms: RoomEntry[] = [];

  for (const pattern of patterns) {
    const glob = new Bun.Glob(pattern);
    for await (const match of glob.scan({ cwd: palaceRoot, absolute: false })) {
      // Room dir is the parent of CLAUDE.md
      const roomDir = match.replace(/\/CLAUDE\.md$/, "");

      // Deduplicate (depth-2 and depth-3 patterns may overlap)
      if (seen.has(roomDir)) continue;
      seen.add(roomDir);

      const fullPath = join(palaceRoot, match);
      let content: string;
      try {
        content = readFileSync(fullPath, "utf-8");
      } catch {
        continue;
      }

      // Skip files without **Status**: line (not room format)
      if (!content.includes("**Status**:")) continue;

      const status = parseStatus(content);
      const now = parseNow(content, 60);

      rooms.push({
        name: roomDir.split("/").pop()!,
        path: roomDir,
        category: categoryFromPath(roomDir),
        status: status.emoji ?? status.text.split(/\s+/)[0] ?? "",
        now,
      });
    }
  }

  return rooms;
}

/**
 * Scan all rooms and generate INDEX.md content.
 *
 * Groups by category, sorts alphabetically within each category.
 * Returns the full markdown string.
 *
 * @param palaceRoot - Absolute path to the palace root directory
 * @returns Complete INDEX.md content as a string
 */
export async function generateIndex(palaceRoot: string): Promise<string> {
  const rooms = await scanRooms(palaceRoot);

  // Group rooms by category
  const groups = new Map<string, RoomEntry[]>();
  for (const room of rooms) {
    const existing = groups.get(room.category);
    if (existing) {
      existing.push(room);
    } else {
      groups.set(room.category, [room]);
    }
  }

  // Sort categories alphabetically
  const sortedCategories = [...groups.keys()].sort();

  // Sort rooms alphabetically within each category
  for (const entries of groups.values()) {
    entries.sort((a, b) => a.name.localeCompare(b.name));
  }

  // Build markdown
  const timestamp = new Date().toISOString();
  const lines: string[] = [
    "# Palace Directory",
    "",
    "> Generated by `memsudo index rebuild` — do not edit",
    `> Last rebuilt: ${timestamp}`,
  ];

  for (const category of sortedCategories) {
    const entries = groups.get(category)!;
    const count = entries.length;
    const roomWord = count === 1 ? "room" : "rooms";

    lines.push("");
    lines.push(`## ${category} (${count} ${roomWord})`);
    lines.push("");
    lines.push("| Room | Status | Now |");
    lines.push("|------|--------|-----|");

    for (const room of entries) {
      const nowDisplay = room.now || "";
      lines.push(
        `| [${room.name}](${room.path}/) | ${room.status} | ${nowDisplay} |`
      );
    }
  }

  const totalRooms = rooms.length;
  const totalCategories = sortedCategories.length;
  const roomWord = totalRooms === 1 ? "room" : "rooms";
  const catWord = totalCategories === 1 ? "category" : "categories";

  lines.push("");
  lines.push("---");
  lines.push(
    `Total: ${totalRooms} ${roomWord} across ${totalCategories} ${catWord}`
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Write INDEX.md to palace root.
 *
 * Generates the index content and writes it to {palaceRoot}/INDEX.md.
 *
 * @param palaceRoot - Absolute path to the palace root directory
 * @returns Object with roomCount and categoryCount
 */
export async function rebuildIndex(
  palaceRoot: string
): Promise<{ roomCount: number; categoryCount: number }> {
  const content = await generateIndex(palaceRoot);

  // Count rooms and categories from the generated content
  const categoryMatches = content.match(/^## .+ \(\d+ rooms?\)$/gm);
  const categoryCount = categoryMatches ? categoryMatches.length : 0;

  const roomMatches = content.match(/^\| \[/gm);
  const roomCount = roomMatches ? roomMatches.length : 0;

  writeFileSync(join(palaceRoot, "INDEX.md"), content, "utf-8");

  return { roomCount, categoryCount };
}
