/**
 * init.ts — Initialize a new memsudo palace in the current directory.
 *
 * Creates the full palace structure: directories, INDEX.md, CLAUDE.md,
 * .gitignore, scripts, hooks, skills, and sample files.
 *
 * Zero runtime dependencies — Bun fs + path only.
 */

import { existsSync, readFileSync, writeFileSync, appendFileSync } from "fs";
import { mkdir } from "fs/promises";
import { join, basename, resolve } from "path";

// ---------------------------------------------------------------------------
// Args parsing
// ---------------------------------------------------------------------------

function parseName(args: string[]): string {
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--name" && i + 1 < args.length) {
      return args[i + 1];
    }
  }
  // Default: current directory basename
  return basename(resolve("."));
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

function indexTemplate(): string {
  return `# Palace Directory

> Generated by \`memsudo index rebuild\` — do not edit
> Last rebuilt: (not yet)

<!-- No rooms yet. Run: memsudo room create <path> -->
`;
}

function claudeMdTemplate(name: string): string {
  return `# ${name}

## Rules

1. **CLAUDE.md** is the status file per room — Claude Code auto-loads it
2. **changelog.md** is append-only — add 1 line per event with emoji
3. **sessions.md** is append-only — add narrative per session
4. **INDEX.md** is generated — never edit manually
5. **.secrets/** is local only — never commit, never read aloud
6. After work in a room: update CLAUDE.md (Status + Now), append changelog.md

## Navigation

1. Read INDEX.md for palace overview
2. Read {category}/{room}/CLAUDE.md for room details
3. Use ## Links section to find related rooms and repos

## Emoji

| Status | Changelog |
|--------|-----------|
| 🟢 Active | ✅ Done |
| 🟡 Paused | ❌ Failed |
| 🔴 Blocked | 🔄 Changed |
| | 📋 Submitted |
| | 🐛 Bug fix |
| | 💡 Decision |
`;
}

function gitignoreEntries(): string {
  return `.secrets/
memsudo.yaml
`;
}

function sampleReadme(): string {
  return `# .sample/

This directory contains example/template files for secrets managed by \`memsudo vault\`.

Each file is named \`{KEY}.example\` and shows the expected format.
To set an actual secret, run:

\`\`\`bash
memsudo vault set KEY "value"
\`\`\`

The real values live in \`.secrets/\` (gitignored, never committed).
`;
}

function sessionStartScript(): string {
  return `#!/bin/bash
# session-start.sh — Run at the start of each Claude Code session.
# Installed by memsudo into linked repos via .claude/hooks.json.
#
# Reads memsudo.yaml from the repo root, finds the palace room,
# and prints the room's CLAUDE.md as system context.

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
YAML_FILE="$REPO_ROOT/memsudo.yaml"

if [ ! -f "$YAML_FILE" ]; then
  exit 0
fi

# Parse palace and room from YAML (simple grep, no yq dependency)
PALACE=$(grep '^palace:' "$YAML_FILE" | sed 's/^palace:[[:space:]]*//')
ROOM=$(grep '^room:' "$YAML_FILE" | sed 's/^room:[[:space:]]*//')

if [ -z "$PALACE" ] || [ -z "$ROOM" ]; then
  exit 0
fi

CLAUDE_MD="$PALACE/$ROOM/CLAUDE.md"

if [ -f "$CLAUDE_MD" ]; then
  echo "--- memsudo room context ---"
  cat "$CLAUDE_MD"
  echo "--- end memsudo context ---"
fi
`;
}

function watchInboxScript(): string {
  return `#!/bin/bash
# watch-inbox.sh — Monitor inbox/messages/pending/ for new messages.
# Moves processed messages to inbox/messages/done/ or inbox/messages/failed/.

PALACE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PENDING="$PALACE_ROOT/inbox/messages/pending"
DONE="$PALACE_ROOT/inbox/messages/done"
FAILED="$PALACE_ROOT/inbox/messages/failed"

if [ ! -d "$PENDING" ]; then
  echo "No pending directory found at $PENDING"
  exit 1
fi

count=0
for msg in "$PENDING"/*.md; do
  [ -f "$msg" ] || continue
  filename="$(basename "$msg")"
  echo "Processing: $filename"
  # Move to done (override with custom processing logic as needed)
  mv "$msg" "$DONE/$filename"
  count=$((count + 1))
done

echo "Processed $count message(s)."
`;
}

function watchHealthScript(): string {
  return `#!/bin/bash
# watch-health.sh — Quick health check for a memsudo palace.
# Verifies required files and directories exist.

PALACE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

errors=0

check_file() {
  if [ ! -f "$PALACE_ROOT/$1" ]; then
    echo "MISSING: $1"
    errors=$((errors + 1))
  fi
}

check_dir() {
  if [ ! -d "$PALACE_ROOT/$1" ]; then
    echo "MISSING: $1/"
    errors=$((errors + 1))
  fi
}

check_file "INDEX.md"
check_file "CLAUDE.md"
check_file ".gitignore"
check_dir "areas"
check_dir "lab"
check_dir "incubate"
check_dir "memory"
check_dir "inbox"
check_dir "outbox"
check_dir "archive"
check_dir ".secrets"

if [ $errors -eq 0 ]; then
  echo "Palace health: OK"
else
  echo "Palace health: $errors issue(s) found"
  exit 1
fi
`;
}

function hooksJsonTemplate(palaceRoot: string): string {
  const scriptPath = join(palaceRoot, "scripts", "session-start.sh");
  const hooks = {
    hooks: {
      SessionStart: [
        {
          matcher: "startup|resume",
          hooks: [
            {
              type: "command",
              command: `bash ${scriptPath}`,
              timeout: 10,
            },
          ],
        },
      ],
    },
  };
  return JSON.stringify(hooks, null, 2) + "\n";
}

function recapSkillTemplate(): string {
  return `---
name: recap
description: Session start orientation — read palace state and current focus
---

# /recap

Read the palace INDEX.md and current room CLAUDE.md to orient at session start.

## Steps

1. Read INDEX.md for palace overview
2. Identify the most recently updated rooms (by **Updated**: field)
3. Read the top 3 most recent rooms' CLAUDE.md
4. Summarize current state: what is active, paused, or blocked
5. Suggest what to work on based on ## Next priorities
`;
}

function standupSkillTemplate(): string {
  return `---
name: standup
description: Daily standup — summarize yesterday and plan today
---

# /standup

Quick daily check across the palace.

## Steps

1. Read INDEX.md for full room list
2. Check changelog.md in active rooms for recent entries
3. Summarize: what was done yesterday, what is planned today
4. Flag any blocked rooms that need attention
5. Output a brief standup summary
`;
}

function wrapSkillTemplate(): string {
  return `---
name: wrap
description: End-of-session wrap — update room state and write handoff
---

# /wrap

End the current session cleanly.

## Steps

1. Update the current room's CLAUDE.md:
   - Set **Updated**: to today
   - Update ## Now with current state
   - Update ## Next with remaining priorities
2. Append a session entry to sessions.md
3. Append changelog entries for work done
4. Write a handoff note to inbox/handoff/ if needed
5. Run \`memsudo index rebuild\` to update INDEX.md
`;
}

// ---------------------------------------------------------------------------
// Directory + file lists
// ---------------------------------------------------------------------------

const DIRECTORIES = [
  "areas",
  "areas/clients",
  "areas/jobs",
  "areas/personal",
  "areas/tools",
  "lab",
  "incubate",
  "memory",
  "memory/resonance",
  "memory/learnings",
  "memory/retrospectives",
  "memory/plans",
  "writing",
  "inbox",
  "inbox/handoff",
  "inbox/messages",
  "inbox/messages/pending",
  "inbox/messages/done",
  "inbox/messages/failed",
  "outbox",
  "archive",
  ".secrets",
  ".sample",
  "scripts",
  ".claude",
  ".claude/skills",
  ".claude/skills/recap",
  ".claude/skills/standup",
  ".claude/skills/wrap",
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export async function initCommand(args: string[]): Promise<void> {
  const name = parseName(args);
  const root = resolve(".");

  // Safety: if INDEX.md already exists, refuse to re-init
  if (existsSync(join(root, "INDEX.md"))) {
    console.error(
      `\u2717 Palace already initialized (INDEX.md exists). Remove it to re-init.`
    );
    process.exit(1);
  }

  let dirCount = 0;
  let fileCount = 0;

  // 1. Create all directories
  for (const dir of DIRECTORIES) {
    const dirPath = join(root, dir);
    if (!existsSync(dirPath)) {
      await mkdir(dirPath, { recursive: true });
      dirCount++;
    }
  }

  // 2. Create INDEX.md
  writeFileSync(join(root, "INDEX.md"), indexTemplate(), "utf-8");
  fileCount++;

  // 3. Create CLAUDE.md
  writeFileSync(join(root, "CLAUDE.md"), claudeMdTemplate(name), "utf-8");
  fileCount++;

  // 4. Handle .gitignore — append if exists, create if not
  const gitignorePath = join(root, ".gitignore");
  const entries = gitignoreEntries();

  if (existsSync(gitignorePath)) {
    const existing = readFileSync(gitignorePath, "utf-8");
    const linesToAdd: string[] = [];

    for (const entry of entries.split("\n").filter((l) => l.length > 0)) {
      // Check if entry already present (exact line match)
      const lines = existing.split("\n").map((l) => l.trim());
      if (!lines.includes(entry)) {
        linesToAdd.push(entry);
      }
    }

    if (linesToAdd.length > 0) {
      const separator = existing.endsWith("\n") ? "" : "\n";
      appendFileSync(
        gitignorePath,
        separator + linesToAdd.join("\n") + "\n",
        "utf-8"
      );
    }
    // Don't count as new file since it already existed
  } else {
    writeFileSync(gitignorePath, entries, "utf-8");
    fileCount++;
  }

  // 5. Create .sample/README.md
  writeFileSync(join(root, ".sample", "README.md"), sampleReadme(), "utf-8");
  fileCount++;

  // 6. Create scripts
  const scripts: Array<{ name: string; content: string }> = [
    { name: "session-start.sh", content: sessionStartScript() },
    { name: "watch-inbox.sh", content: watchInboxScript() },
    { name: "watch-health.sh", content: watchHealthScript() },
  ];

  for (const script of scripts) {
    const scriptPath = join(root, "scripts", script.name);
    writeFileSync(scriptPath, script.content, "utf-8");
    fileCount++;
  }

  // Make scripts executable
  const { chmod } = await import("fs/promises");
  for (const script of scripts) {
    await chmod(join(root, "scripts", script.name), 0o755);
  }

  // 7. Create .claude/hooks.json
  writeFileSync(
    join(root, ".claude", "hooks.json"),
    hooksJsonTemplate(root),
    "utf-8"
  );
  fileCount++;

  // 8. Create skill files
  const skills: Array<{ path: string; content: string }> = [
    {
      path: ".claude/skills/recap/SKILL.md",
      content: recapSkillTemplate(),
    },
    {
      path: ".claude/skills/standup/SKILL.md",
      content: standupSkillTemplate(),
    },
    {
      path: ".claude/skills/wrap/SKILL.md",
      content: wrapSkillTemplate(),
    },
  ];

  for (const skill of skills) {
    writeFileSync(join(root, skill.path), skill.content, "utf-8");
    fileCount++;
  }

  console.log(
    `\u2713 Palace '${name}' initialized (${dirCount} dirs, ${fileCount} files)`
  );
}
